Feat/change name
su-its/its-discord pull request #36
Opened 2024-05-14 06:28 UTC by KikyoNanakusa

resolve #34 
# やったこと
authコマンドを実行するとサーバーでの表示名がデータベースの表示名に変更されるように機能追加
それについてドキュメントを追加

# 動作確認
自前のサーバーで動作確認済み

2024-05-14 08:27 UTC, KinjiKawaguchi requested changes
これってどのタイミングで本名になる？
あと、こちらがコマンドしたら全員一旦本名になるがあると嬉しい

2024-05-14 08:44 UTC, araaki12345 commented
どのタイミングか？→authコマンドを実行した際に名前が変更される
管理者が全員を本名にする機能がほしい→実装します。
by 七草

2024-06-05 14:41 UTC, KinjiKawaguchi approved these changes

2024-06-05 14:41 UTC, KinjiKawaguchi commented on src/commands/rename_all.ts
> +export default renameALL;
```suggestion
export default renameALL;

```

2024-06-05 14:41 UTC, KinjiKawaguchi commented on src/utils/checkMemberRole.ts
> +export default checkIsAdmin;
```suggestion
export default checkIsAdmin;

```

2024-06-05 14:41 UTC, merged